### ISSUE TITLE
collada_parser build failure on debian jessie

### ISSUE THREAD

**Issue by sloretz** [ros/collada_urdf#7] opened 2017-05-11 15:43 UTC
From ros/robot_model#166

Collada_parser failed building on my raspberry pi 3 (debian jessie). I ran into the following error:

```
....
/home/pi/ros_catkin_ws/src/robot_model/collada_parser/src/collada_parser.cpp:2434:59: error: request for member ‘end’ in ‘((urdf::ColladaModelReader*)this)->urdf::ColladaModelReader::_model.boost::shared_ptr<T>::operator-><urdf::ModelInterface>()->urdf::ModelInterface::joints_’, which is of non-class type ‘int’
         if (_model->joints_.find(name) == _model->joints_.end()) {
                                                           ^
/home/pi/ros_catkin_ws/src/robot_model/collada_parser/src/collada_parser.cpp:2437:38: error: request for member ‘find’ in ‘((urdf::ColladaModelReader*)this)->urdf::ColladaModelReader::_model.boost::shared_ptr<T>::operator-><urdf::ModelInterface>()->urdf::ModelInterface::joints_’, which is of non-class type ‘int’
             pjoint = _model->joints_.find(name)->second;
                                      ^
CMakeFiles/collada_parser.dir/build.make:54: recipe for target 'CMakeFiles/collada_parser.dir/src/collada_parser.cpp.o' failed
make[2]: *** [CMakeFiles/collada_parser.dir/src/collada_parser.cpp.o] Error 1
CMakeFiles/Makefile2:91: recipe for target 'CMakeFiles/collada_parser.dir/all' failed
make[1]: *** [CMakeFiles/collada_parser.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'collada_parser': 
  Command '['/opt/ros/indigo/env.sh', 'make', '-j1']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/pi/ros_catkin_ws/build_isolated/collada_parser && /opt/ros/indigo/env.sh make -j1
```

Re-running the make command gives:

```
[ 50%] Building CXX object CMakeFiles/collada_parser.dir/src/collada_parser.cpp.o
CMakeFiles/collada_parser.dir/build.make:54: recipe for target 'CMakeFiles/collada_parser.dir/src/collada_parser.cpp.o' failed
CMakeFiles/Makefile2:91: recipe for target 'CMakeFiles/collada_parser.dir/all' failed
Makefile:127: recipe for target 'all' failed
```

I raised the question the issue also [here](http://answers.ros.org/question/247523/collada_parser-build-failed-on-raspberry-pi-3-jessie-debian-ros-indigo/).

**Comment by clalancette** [comment] 2017-07-27 21:28
I don't think that this is a problem anymore; at least, I can't reproduce this on Jessie with Indigo.  I'm going to close this out for now; feel free to reopen if this is still a problem.

**Closed as completed** 2017-07-27 21:28 UTC
