### ISSUE TITLE
urdf_to_collada: cylinder geometry not generated properly

### ISSUE THREAD

**Issue by bkinman** [ros/collada_urdf#20] opened 2017-10-24 18:03 UTC
Howdy!

It seems to be the case that `urdf_to_collada` is not generating mesh geometry properly for my urdf file.

Upon inspection of the resulting dae file in both the openrave gui, and in meshlab, I'm seeing that the number of vertices does not seem to be sufficient to represent the cylinder geometries in the urdf file.

I've tested `urdf_to_collada` on the pr2 urdf that is included in the test directory, and it seems to be working properly. However, I did not look too closely at how the cylinders were generated.

I witness this behavior both in the version of `urdf_to_collada` in kinetic's `robot_model` package, and also at the head of the current kinetic-devel branch.

I've attached my urdf file, and resulting collada file for reference, as well as an image of the output as viewed in the openrave viewer.

Is this a bug?

[greppy_arm.urdf.txt](https://github.com/ros/collada_urdf/files/1411908/greppy_arm.urdf.txt)
[out.dae.txt](https://github.com/ros/collada_urdf/files/1411909/out.dae.txt)
![screenshot from 2017-10-24 10-50-32](https://user-images.githubusercontent.com/3754452/31959855-c27cc464-b8aa-11e7-9d3b-030c1b59b40a.png)

**Comment by sloretz** [comment] 2017-10-24 18:20
Thanks for the bug report! I don't think I will have time to investigate this week. Would you mind checking if a URDF with a single link with a single cylinder reproduces the problem?

**Comment by bkinman** [comment] 2017-10-24 18:43
Indeed, here are the results for a single link.

[foobar_arm_minimal.urdf.txt](https://github.com/ros/collada_urdf/files/1412066/foobar_arm_minimal.urdf.txt)
[out_minimal.dae.txt](https://github.com/ros/collada_urdf/files/1412067/out_minimal.dae.txt)
![screenshot from 2017-10-24 11-40-45](https://user-images.githubusercontent.com/3754452/31961749-7e4f4248-b8b0-11e7-8b03-e53d6665b987.png)

**Comment by sloretz** [comment] 2017-10-24 19:02
Thanks for the single link case! It looks like [`geometric_shapes`](http://wiki.ros.org/geometric_shapes) has a hard coded parameter defining the number of triangles to use when creating a mesh for a cylinder. It results in a pretty small number of triangles for a cylinder of radius 0.05.  A workaround would be to build `geometric_shapes` from source and increase the value.

https://github.com/ros-planning/geometric_shapes/blob/66352a742520f71e19a32139ec7463dcefe3b451/src/mesh_operations.cpp#L515-L516

If `createMeshFromShape(Cylinder)` parameterized this value, it would need to be passed through `urdf_to_collada` [here](https://github.com/ros/collada_urdf/blob/e426aad7770d7fc3a548fc201ebc58dbe6b1e6e0/collada_urdf/src/collada_urdf.cpp#L1308).

I don't think I will be able to implement this anytime soon. If you happen to fix it a pull request would be welcome.

**Comment by bkinman** [comment] 2017-10-24 20:31
Awesome, got it to work! Set the magic number to 1000 instead of 100. It may be easier to just make the number of vertices dependent on the cylinder radius; That would prevent any need for exposing an additional parameter. I believe that this is how the sphere is handled. I'll create a pull request as soon as I get a chance.

Thanks!

![screenshot from 2017-10-24 13-28-55](https://user-images.githubusercontent.com/3754452/31966448-946f3a1a-b8bf-11e7-828d-7ff8843b17d6.png)

**Comment by sloretz** [comment] 2017-12-18 16:00
@bkinman Do you know if there has been any movement over at ros/geometric_shapes on exposing the number as a parameter?

**Comment by bkinman** [comment] 2017-12-18 19:38
Unfortunately I do not. If I manage to get back around to collada/urdf with
this project I'm working on I'll create a pull request.

**Comment by rhaschke** [comment] 2018-12-09 10:26
Fixed in https://github.com/ros-planning/geometric_shapes/pull/92

**Comment by sloretz** [comment] 2019-01-23 01:39
Closing since this was solved upstream

**Closed as completed by sloretz** 2019-01-23 01:39 UTC
Labels: enhancement
